GameSetBook/Controllers/BookingController.cs
using GameSetBook.Core.Contracts;
using GameSetBook.Core.Models.Booking;
using GameSetBook.Infrastructure.Models.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using static GameSetBook.Common.RoleConstants;

namespace GameSetBook.Web.Controllers
{
    public class BookingController : BaseController
    {
        private readonly IBookingService bookingService;
        private readonly ICourtService courtService;
        private readonly IClubService clubService;
        private readonly UserManager<ApplicationUser> userManager;

        public BookingController(IBookingService bookingService, ICourtService courtService, IClubService clubService, UserManager<ApplicationUser> userManager)
        {
            this.bookingService = bookingService;
            this.courtService = courtService;
            this.clubService = clubService;
            this.userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] AllBookingsSortingModel model)
        {
            model = await bookingService.GetBookingSortingServiceModelAsync(model, User.Id());

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Book([FromQuery] BookingScheduleViewModel queryModel)
        {

            int courtId = queryModel.CourtId;

            if (!await courtService.ExistAsync(courtId))
            {
                return BadRequest();
            }

            int hour = queryModel.Hour;
            var bookingDate = queryModel.BookingDate;

            if (!await bookingService.AreDateAndHourValidAsync(queryModel.BookingDate, queryModel.Hour, queryModel.CourtId))
            {
                return BadRequest();
            }

            if (await bookingService.BookingExistAsync(queryModel.BookingDate, queryModel.Hour, queryModel.CourtId))
            {
                return BadRequest();
            }

            var user = await userManager.FindByIdAsync(User.Id());


            var model = new BookingCreateFormModel()
            {
                Hour = hour,
                CourtId = courtId,
                BookingDate = bookingDate,
                Price = await courtService.GetPriceAsync(courtId),
                ClientName = user.FirstName + " " + user.LastName,
                PhoneNumber = user.PhoneNumber
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Book(BookingCreateFormModel model)
        {
            int courtId = model.CourtId;

            if (!await courtService.ExistAsync(courtId))
            {
                return BadRequest();
            }

            if (!await bookingService.AreDateAndHourValidAsync(model.BookingDate, model.Hour, model.CourtId))
            {
                return BadRequest();
            }

            if (await bookingService.BookingExistAsync(model.BookingDate, model.Hour, model.CourtId))
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                model.PhoneNumber = string.Empty;
                return View(model);
            }

            model.ClientId = User.Id();

            var clubId = await bookingService.AddAsync(model);

            return RedirectToAction("Schedule", "Club", new { id = clubId, date = model.BookingDate });
        }

        [HttpPost]
        public async Task<IActionResult> Cancel(int id, AllBookingsSortingModel filters)
        {
            if (!await bookingService.ExistByIdAsync(id))
            {
                return BadRequest();
            }

            if (!await bookingService.IsBookingClientAsync(id,User.Id()))
            {
                return Unauthorized();
            }

            if(!await bookingService.IsCancelableAsync(id))
            {
                return BadRequest();
            }

            await bookingService.DeleteAsync(id);

            return RedirectToAction(nameof(Index),filters);
        }

        [HttpGet]
        [Authorize(Roles = ClubOwnerRole)]
        public async Task<IActionResult> OwnerBook([FromQuery] BookingScheduleViewModel queryModel)
        {
            int courtId = queryModel.CourtId;

            if (!await courtService.ExistAsync(courtId))
            {
                return BadRequest();
            }

            if (!await courtService.IsCourtInClubOfTheOwnerAsync(courtId, User.Id()))
            {
                return Unauthorized();
            }

            int hour = queryModel.Hour;
            var bookingDate = queryModel.BookingDate;

            if (await bookingService.BookingExistAsync(queryModel.BookingDate, queryModel.Hour, queryModel.CourtId))
            {
                return BadRequest();
            }

            var model = new BookingCreateFormModel()
            {
                Hour = hour,
                CourtId = courtId,
                BookingDate = bookingDate,
                Price = await courtService.GetPriceAsync(courtId),
            };

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = ClubOwnerRole)]
        public async Task<IActionResult> OwnerBook(BookingCreateFormModel model)
        {
            int courtId = model.CourtId;

            if (!await courtService.ExistAsync(courtId))
            {
                return BadRequest();
            }

            if (await bookingService.BookingExistAsync(model.BookingDate, model.Hour, model.CourtId))
            {
                return BadRequest();
            }

            if (!await courtService.IsCourtInClubOfTheOwnerAsync(courtId, User.Id()))
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model.ClientId = User.Id();
            model.IsBookedByOwnerOrAdmin = true;

            var clubId = await bookingService.AddAsync(model);

            return RedirectToAction("MyClubSchedule", "Club", new { id = clubId, date = model.BookingDate });
        }

        [HttpGet]
        [Authorize(Roles = ClubOwnerRole)]
        public async Task<IActionResult> Edit(int id)
        {
            if (!await bookingService.ExistByIdAsync(id))
            {
                return BadRequest();
            }

            if (!await bookingService.IsClubOwnerAllowedToEditAsync(id, User.Id()))
            {
                return Unauthorized();
            }

            var clubId = await clubService.GetClubIdByOwnerIdAsync(User.Id());

            ViewData["ClubId"] = clubId;

            var model = await bookingService.GetBookingToEditAsync(id);

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = ClubOwnerRole)]
        public async Task<IActionResult> Edit(BookingEditFormModel model)
        {
            if (!await bookingService.ExistByIdAsync(model.Id))
            {
                return BadRequest();
            }

            if (!await bookingService.IsClubOwnerAllowedToEditAsync(model.Id, User.Id()))
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var clubId = await clubService.GetClubIdByOwnerIdAsync(User.Id());

            await bookingService.EditAsync(model);

            return RedirectToAction("MyClubSchedule", "Club", new { id = clubId, date = model.BookingDate });
        }

        [HttpPost]
        [Authorize(Roles = ClubOwnerRole)]
        public async Task<IActionResult> Delete(BookingEditFormModel model)
        {
            if (!await bookingService.ExistByIdAsync(model.Id))
            {
                return BadRequest();
            }

            if (!await bookingService.IsClubOwnerAllowedToEditAsync(model.Id, User.Id()))
            {
                return Unauthorized();
            }

            var clubId = await clubService.GetClubIdByOwnerIdAsync(User.Id());

            await bookingService.DeleteAsync(model.Id);

            return RedirectToAction("MyClubSchedule", "Club", new { id = clubId, date = model.BookingDate });
        }      
    }
}

GameSetBook/Controllers/CourtController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

using GameSetBook.Common.Enums;
using GameSetBook.Common.Enums.EnumExtensions;
using GameSetBook.Core.Contracts;
using GameSetBook.Core.Models.Court;
using static GameSetBook.Common.RoleConstants;

namespace GameSetBook.Web.Controllers
{
    public class CourtController : BaseController
    {
        public readonly ICourtService courtService;
        public readonly IClubService clubService;
        public CourtController(ICourtService courtService, IClubService clubService)
        {
            this.courtService = courtService;
            this.clubService = clubService;
        }

        [HttpGet]
        public async Task<IActionResult> Create(int clubId, int numberOfCourts)
        {
            if (!await clubService.ExsitAsync(clubId))
            {
                return BadRequest();
            }

            if (await clubService.IsClubAproovedAsync(clubId))
            {
                return BadRequest();
            }

            CourtCreateFormModel[] model = new CourtCreateFormModel[numberOfCourts];

            ViewBag.Surfaces = GetSurfaces(); ;

            for (int i = 0; i < numberOfCourts; i++)
            {
                model[i] = new CourtCreateFormModel()
                {
                    ClubId = clubId,
                };
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CourtCreateFormModel[] model)
        {
            var clubId = model[0].ClubId;

            if (!await clubService.ExsitAsync(clubId))
            {
                return BadRequest();
            }

            if (await clubService.ClubHasCourtsAsync(clubId))
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                ViewBag.Surfaces = GetSurfaces();

                return View(model);
            }

            await courtService.CreateInitialAsync(model);

            return RedirectToAction("Index", "Club");
        }

        [HttpGet]
        [Authorize(Roles = ClubOwnerRole)]
        public async Task<IActionResult> Edit(int id)
        {
            if (! await courtService.ExistAsync(id))
            {
                return BadRequest();
            }
            if (!await courtService.IsCourtInClubOfTheOwnerAsync(id, User.Id()))
            {
                return Unauthorized();
            }

            var model = await courtService.GetCourtEditFormModelAsync(id);

            ViewBag.Surfaces = GetSurfaces();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = ClubOwnerRole)]
        public async Task<IActionResult> Edit(CourtEditFormModel model)
        {
            if (!await courtService.ExistAsync(model.Id))
            {
                return BadRequest();
            }

            if (model.ClubOwnerId != User.Id())
            {
                return Unauthorized();
            }

            if (!await courtService.IsCourtInClubOfTheOwnerAsync(model.Id, User.Id()))
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                ViewBag.Surfaces = GetSurfaces();

                return View(model);
            }

            await courtService.EditAsync(model);
            
            return RedirectToAction("MyClub", "Club", new { id = model.ClubId });
        }

        [HttpGet]
        [Authorize(Roles = ClubOwnerRole)]
        public async Task<IActionResult> Add()
        {
            var model = new CourtCreateFormModel()
            {
                ClubId = await clubService.GetClubIdByOwnerIdAsync(User.Id())
            };

            ViewBag.Surfaces = GetSurfaces();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = ClubOwnerRole)]
        public async Task<IActionResult> Add(CourtCreateFormModel model)
        {
            if (!await clubService.ExsitAsync(model.ClubId))
            {
                return BadRequest();
            }

            if(!await clubService.IsTheOwnerOfTheClubAsync(model.ClubId, User.Id()))
            { 
                return Unauthorized(); 
            }

            if (!ModelState.IsValid)
            {
                ViewBag.Surfaces = GetSurfaces();

                return View(model);
            }

            await courtService.AddCourtAsync(model);

            return RedirectToAction("MyClub","Club", new {id=model.ClubId});
        }

        [HttpPost]
        [Authorize(Roles = ClubOwnerRole)]
        public async Task<IActionResult> ChangeStatus(int id)
        {
            if (!await courtService.ExistAsync(id))
            {
                return BadRequest();
            }

            if (!await courtService.IsCourtInClubOfTheOwnerAsync(id, User.Id()))
            {
                return Unauthorized();
            }

            await courtService.ChangeStatusAsync(id);

            var clubId = await clubService.GetClubIdByOwnerIdAsync(User.Id());

            return RedirectToAction("MyClub", "Club", new {id=clubId});
        }

        private static List<SelectListItem> GetSurfaces()
        {
            return Enum.GetValues(typeof(Surface)).Cast<Surface>().Select(v => new SelectListItem
            {
                Text = v.GetDisplayName(),
                Value = ((int)v).ToString()
            }).ToList();
        }
    }
}

GameSetBook/Areas/Admin/Views/Club/Approve.cshtml
@model ClubDetailsAdminViewModel

@{
    ViewBag.Title = "Pending Club Details";
}

<h1 class="text-center pb-3">@ViewBag.Title</h1>

<partial name="_ClubDetailsPartial" model="Model"/>

<div class="row pt-3">
    <div class="col col-3">
        <form asp-area="Admin" asp-controller="Club" asp-action="ApproveClub" method="post">
            <input type="hidden" asp-for="Id" />
            <div class="mb-3 text-center">
                <input class="btn btn-success mb-2 w-100 p-3 fw-bold" type="submit" value="Approve Club" />
            </div>
        </form>
    </div>
    <div class="col col-3">
        <a asp-area="Admin" asp-controller="Club" asp-action="Edit" asp-route-id="@Model.Id" asp-route-returnUrl="@Model.ReturnUrl" class="btn btn-primary mb-2 w-100 p-3 fw-bold">Edit Club Details</a>
    </div>
    <div class="col col-3">
        <button type="button" class="btn btn-danger mb-2 w-100 p-3 fw-bold" data-bs-toggle="modal" data-bs-target="#confirmationModal">
            Delete Club
        </button>
    </div>
    <div class="col col-3">
        <a asp-area="Admin" asp-controller="Court" asp-action="Add" asp-route-clubId="@Model.Id" asp-route-returnUrl="@Model.ReturnUrl" class="btn btn-success mb-2 w-100 p-3 fw-bold">Add Court</a>
    </div>
</div>

<div class="modal fade" id="confirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmationModalLabel">Confirmation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this club?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <form asp-area="Admin" asp-controller="Club" asp-action="Delete" method="post">
                    <input type="hidden" asp-for="Id" />
                    <input type="hidden" asp-for="ClubOwnerId" />
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

GameSetBook/Areas/Admin/Views/Club/Create.cshtml
@model ClubAdminCreateFormModel

@{
    IFormFile file = ViewBag.File;
    IEnumerable<SelectListItem> cities = ViewBag.Cities;
    ViewBag.Title = "Register New Club";
}

<h2 class="text-center">@ViewBag.Title</h2>

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger" role="alert">
        <ul>
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <li>@error.ErrorMessage</li>
            }
        </ul>
    </div>
}

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="Create" method="post" enctype="multipart/form-data">

            <div class="mb-3">
                <label asp-for="ClubOwnerEmail" class="form-label"></label>
                <input asp-for="ClubOwnerEmail" class="form-control" aria-required="true" />
                <span asp-validation-for="ClubOwnerEmail" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" aria-required="true" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Description" class="form-label-add-edit"></label>
                <textarea asp-for="Description" class="form-control" aria-required="true" rows="4"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="WorkingTimeStart" class="form-label"></label>
                <input asp-for="WorkingTimeStart" class="form-control" aria-required="true" />
                <span asp-validation-for="WorkingTimeStart" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="WorkingTimeEnd" class="form-label"></label>
                <input asp-for="WorkingTimeEnd" class="form-control" aria-required="true" />
                <span asp-validation-for="WorkingTimeEnd" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Address" class="form-label"></label>
                <input asp-for="Address" class="form-control" aria-required="true" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="CityId" class="form-label"></label>
                <select asp-for="CityId" class="form-select" asp-items="cities"></select>
                <span asp-validation-for="CityId" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" class="form-control" aria-required="true" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="PhoneNumber" class="form-label"></label>
                <input asp-for="PhoneNumber" class="form-control" aria-required="true" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="NumberOfCoaches" class="form-label"></label>
                <input asp-for="NumberOfCoaches" class="form-control" aria-required="true" />
                <span asp-validation-for="NumberOfCoaches" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="NumberOfCourts" class="form-label"></label>
                <input asp-for="NumberOfCourts" class="form-control" aria-required="true" />
                <span asp-validation-for="NumberOfCourts" class="text-danger"></span>
            </div>

            <div class="row">
                <div class="col-4">
                    <label>
                        Parking
                        <input type="checkbox" asp-for="HasParking" />
                        <span asp-validation-for="HasParking" class="text-danger"></span>
                    </label>
                </div>
                <div class="col-4">
                    <label>
                        Tennis Shop
                        <input type="checkbox" asp-for="HasShop" />
                        <span asp-validation-for="HasShop" class="text-danger"></span>
                    </label>
                </div>
                <div class="col-4">
                    <label>
                        Showers
                        <input type="checkbox" asp-for="HasShower" />
                        <span asp-validation-for="HasShower" class="text-danger"></span>
                    </label>
                </div>
            </div>
            <hr />
            <div class="mb-3">
                <label class="form-label-add-edit"></label>
                <input type="file" name="file" class="form-control-file" accept="image/*" aria-describedby="file" />
                <small id="file" class="form-text text-muted">Upload an image for your club logo.</small>
            </div>

            <div class="mb-3 text-center">
                <input class="btn btn-primary mb-2 w-100 p-3 fw-bold" type="submit" value="Register" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GameSetBook/Areas/Admin/Views/Club/Details.cshtml
@model ClubDetailsAdminViewModel

@{
    ViewBag.Title = $"Manage Club";
}

<div>
    @await Component.InvokeAsync(nameof(ClubMenuComponent), new { clubId = Model.Id })
</div>

<h1 class="text-center pb-3">@ViewBag.Title</h1>
@if (Model.IsAproovedByAdmin==false)
{
    <h3 class="text-center text-danger">
        Important! This club is pending for approval!
    </h3>
    <h4 class="text-center"><a asp-area="Admin" asp-controller="Club" asp-action="Approve" asp-route-id="@Model.Id" class="">Click here for more details</a></h4>
}
<partial name="_ClubDetailsPartial" model="Model" />

<div class="row pt-3">
    <div class="col col-3">
        <a asp-area="Admin" asp-controller="Club" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary mb-2 w-100 p-3 fw-bold">Edit CLub Details</a>
    </div>
    <div class="col col-3">
        <button type="button" class="btn btn-danger mb-2 w-100 p-3 fw-bold" data-bs-toggle="modal" data-bs-target="#confirmationModal">
            Delete Club
        </button>
    </div>
    <div class="col col-3">
        <a asp-area="Admin" asp-controller="Club" asp-action="HardDelete" asp-route-id="@Model.Id" class="btn btn-dark mb-2 w-100 p-3 fw-bold">Hard Delete Club</a>
    </div>
    <div class="col col-3">
        <a asp-area="Admin" asp-controller="Court" asp-action="Add" asp-route-clubId="@Model.Id" class="btn btn-success mb-2 w-100 p-3 fw-bold">Add Court</a>
    </div>
</div>

<div class="modal fade" id="confirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmationModalLabel">Confirmation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this club?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <form asp-area="Admin" asp-controller="Club" asp-action="Delete" method="post">
                    <input type="hidden" asp-for="Id" />
                    <input type="hidden" asp-for="ClubOwnerId" />
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

GameSetBook/Areas/Admin/Views/Club/Schedule.cshtml
@model ClubScheduleAdminServiceModel


@{
    var clubInfo = ViewData["ClubInfo"];

    DateTime? cuurentDate = Model.Date;
    int WorkingTimeStart = Model.WorkingHourStart;
    int WorkingTimeEnd = Model.WorkingHourEnd;
    int clubId = Model.Id;
    ViewBag.Title = $"{Model.Name} Schedule";
}

<div>
    @await Component.InvokeAsync(nameof(ClubMenuComponent), new { clubId = Model.Id })
</div>

@if (cuurentDate != null)
{
    <h2 class="text-center">@ViewBag.Title for @cuurentDate.Value.ToShortDateString() @cuurentDate.GetValueOrDefault().DayOfWeek</h2>
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form id="filterForm" asp-action="Schedule" method="get">
                <div class="row">
                    <div class="form-actions no-color col-auto">
                        <div class="row align-items-center">
                            <div class="col-auto">
                                @if (Model.Date != null)
                                {
                                    <a asp-controller="Club" asp-action="Schedule" asp-route-id="@clubId" asp-route-date="@Model.Date.Value.AddDays(-1).ToString("yyy-MM-dd")" class="btn btn-primary"> <i class="fa fa-arrow-circle-o-left"></i> Previous Day</a>
                                }
                            </div>
                            <div class="col">
                                <input asp-for="Date" class="form-control" type="date" value="@(Model.Date!=null ? Model.Date.Value.ToString("yyy-MM-dd") : null)" />
                            </div>
                            <div class="col-auto">
                                @if (Model.Date != null)
                                {
                                    <a asp-controller="Club" asp-action="Schedule" asp-route-id="@clubId" asp-route-date="@Model.Date.Value.AddDays(1).ToString("yyy-MM-dd")" class="btn btn-primary">Next Day <i class="fa fa-arrow-circle-o-right"></i></a>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </form>

            <div class=" row mt-4">
                <div class="col-sm-10">
                    <div class="text-center">
                        <table class="table table-sm table-hover table-bordered table-responsive-md">
                            <thead class="table-dark">
                                <tr>
                                    <th>
                                        <i class="fa fa-calendar" style="font-size:24px"></i>
                                        @if (cuurentDate != null)
                                        {
                                            <p>@cuurentDate.Value.ToShortDateString()</p>
                                        }
                                    </th>
                                    @foreach (var court in Model.Courts)
                                    {
                                        <th>
                                            <strong>@court.Name</strong>
                                            <br />
                                            <small class="text-sm-center">@court.Surface </small>
                                            <br />

                                            @if (court.IsIndoor)
                                            {
                                                <small class="text-sm-start">
                                                    Indoor
                                                </small>
                                            }
                                            @if (court.IsLighted)
                                            {
                                                <small class="text-sm-end">
                                                    Lighted
                                                </small>
                                            }
                                        </th>
                                    }
                                </tr>
                            </thead>
                            <tbody class="table-group-divider">
                                @for (int i = @WorkingTimeStart; i < WorkingTimeEnd; i++)
                                {
                                    <tr>
                                        <th>
                                            @if (i < 10)
                                            {
                                                <span><i class="fa fa-clock-o"></i>0@(i):00</span>
                                            }
                                            else
                                            {
                                                <span><i class="fa fa-clock-o"></i>@(i):00</span>
                                            }
                                        </th>
                                        @foreach (var court in Model.Courts)
                                        {
                                            var booking = null as BookingScheduleAdminServiceModel;
                                            foreach (var booked in court.Bookings)
                                            {

                                                if (booked.Hour == i)
                                                {
                                                    booking = booked;
                                                    break;
                                                }
                                            }
                                            <td>
                                                @if (booking != null && booking.IsAvailable)
                                                {
                                                    <a asp-area="Admin" asp-controller="Booking" asp-action="Book" asp-route-CourtId="@court.Id" asp-route-Hour="@booking.Hour" asp-route-BookingDate="@booking.BookingDate" asp-route-price="@court.Price" asp-route-clubId="@clubId" class="btn btn-sm btn-success w-100">Book/<small>@(court.Price)BGN</small></a>
                                                }
                                                else
                                                {
                                                    if (booking != null)
                                                    {
                                                        <a asp-area="Admin" asp-controller="Booking" asp-action="Edit" asp-route-id="@booking.Id" class="btn btn-sm btn-danger w-100">Booked/<small>@(court.Price)BGN</small></a>
                                                    }
                                                }
                                            </td>
                                        }
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
}