GameSetBook/Areas/Admin/Controllers/CityController.cs
using GameSetBook.Core.Contracts.Admin;
using GameSetBook.Core.Models.Admin.City;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using static GameSetBook.Common.ErrorMessageConstants;

namespace GameSetBook.Web.Areas.Admin.Controllers
{
    public class CityController : BaseController
    {
        private readonly ICityServiceAdmin cityService;
        private readonly ICountryServiceAdmin countryService;

        public CityController(ICityServiceAdmin cityService, ICountryServiceAdmin countryService)
        {
            this.cityService = cityService;
            this.countryService = countryService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var model = await cityService.GetAllCitiesAsync();

            model=model.OrderBy(c=>c.CountryName).ToList();

            return View(model);
        }

        public async Task<IActionResult> Details(int id)
        {
            if (!await cityService.ExistById(id))
            {
                return BadRequest();
            }

            var mdoel = await cityService.GetCityDetailsAsync(id);

            return View(mdoel);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new CityAddAdminFormModel();

            var counties = await countryService.GetAllCountriesAsync();
            ViewBag.Countries = counties.Select(x => new SelectListItem(x.Name, x.Id.ToString()));

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(CityAddAdminFormModel model)
        {
            if (await cityService.ExistByNameAsync(model.Name, model.CountryId))
            {
                ModelState.AddModelError(string.Empty, string.Format(CityWithNameExist, model.Name));
            }

            if (!ModelState.IsValid)
            {
                var counties = await countryService.GetAllCountriesAsync();
                ViewBag.Countries = counties.Select(x => new SelectListItem(x.Name, x.Id.ToString()));
                return View(model);
            }

            await cityService.AddAsync(model);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (!await cityService.ExistById(id))
            {
                return BadRequest();
            }

            await cityService.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

GameSetBook/Areas/Admin/Controllers/CountryController.cs
using GameSetBook.Core.Contracts.Admin;
using GameSetBook.Core.Models.Admin.Country;
using Microsoft.AspNetCore.Mvc;

using static GameSetBook.Common.ErrorMessageConstants;

namespace GameSetBook.Web.Areas.Admin.Controllers
{
    public class CountryController : BaseController
    {
        private readonly ICountryServiceAdmin countryService;

        public CountryController(ICountryServiceAdmin countryService)
        {
            this.countryService = countryService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var model = await countryService.GetAllCountriesAsync();

            return View(model);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var model = new CountryAddAdminFormModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(CountryAddAdminFormModel model)
        {
            if (await countryService.ExistByNameAsync(model.Name))
            {
                ModelState.AddModelError(string.Empty, string.Format(CountryWithNameExist, model.Name));
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await countryService.AddAsync(model);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (!await countryService.ExistAsync(id))
            {
                return BadRequest();
            }

            var model = await countryService.GetCountryDetailAsync(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (!await countryService.ExistAsync(id))
            {
                return BadRequest();
            }

            await countryService.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

GameSetBook/Areas/Admin/Views/Country/Add.cshtml
@model CountryAddAdminFormModel

@{
    ViewBag.Title = $"Add Country";
}

<h1 class="text-center">@ViewBag.Title</h1>

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger" role="alert">
        <ul>
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <li>@error.ErrorMessage</li>
            }
        </ul>
    </div>
}

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-area="Admin" asp-controller="Country" asp-action="Add" method="post">
            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" aria-required="true" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mb-3 text-center">
                <div class="row align-items-center">
                    <div class="col">
                        <input class="btn btn-primary mb-2 w-100 p-3 fw-bold" type="submit" value="Add" />
                    </div>
                    <div class="col">
                        <a asp-action="Index" class="btn btn-secondary mb-2 w-100 p-3 fw-bold">Back</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

GameSetBook/Areas/Admin/Views/Country/Details.cshtml
@model CountryDetailsAdminViewModel
@{
    ViewBag.Title = "Country Details";
}

<h1>@Model.Name Details</h1>

<h2>Cities</h2>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var city in Model.Cities)
        {
            <tr>
                <td>@city.Name</td>
                <td>
                    <a asp-controller="City" asp-action="Details" asp-route-id="@city.Id">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<h2>Clubs</h2>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>City</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var club in Model.Clubs)
        {
            <tr>
                <td>@club.Name</td>
                <td>@club.City</td>
                <td>
                    <a asp-controller="Club" asp-action="Details" asp-route-id="@club.Id">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="form-group">
    <button type="button" class="btn btn-danger mb-2 w-25 p-3 fw-bold" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal">
        Delete Country
    </button>
</div>

<form asp-controller="Country" asp-action="Delete" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmDeleteModalLabel">Confirm Delete</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <strong class="text-danger">Are you sure you want to delete this country? This action cannot be undone and all data related to this country will be permanently deleted!!!</strong>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
            </div>
        </div>
    </div>
</form>

GameSetBook/Areas/Admin/Views/Country/Index.cshtml
@model IEnumerable<CountryAdminServiceModel>
@{
    ViewBag.Title = "All Countries";
}

<h1 class="text-center">@ViewBag.Title</h1>

<div class="text-center mb-3">
    <a asp-area="Admin" asp-controller="Country" asp-action="Add" class="btn btn-success">
        <i class="fa fa-plus-circle"></i> Add Country
    </a>
</div>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var country in Model)
        {
            <tr>
                <td>@country.Id</td>
                <td>@country.Name</td>
                <td>
                    <a asp-controller="Country" asp-action="Details" asp-route-id="@country.Id" class="btn btn-info">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}